[package]
name = "lotro_parser"
version = "0.1.0"
authors = ["Celeo <celeodor@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.1.3"
lazy_static = "1.3.0"
ws = "0.8.0"
env_logger = "0.6.1"
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.39"
